def get_transparency_label(attribution):
    if attribution == "likely_ai":
        return "Likely AI-generated: Our system found strong signals that this content may have been generated by AI. This label is based on automated analysis and may be appealed by the creator."

    if attribution == "likely_human":
        return "Likely human-written: Our system found strong signals that this content was written by a person. This label is based on automated analysis and is not a guarantee of authorship."

    return "Attribution uncertain: Our system found mixed signals about whether this piece was AI-generated or human-written. This label is not a final judgment, and the creator may appeal."